### ISSUE TITLE
An explanation about variables

### ISSUE THREAD

**Issue by ghost** [MrChrisJohnson/deep-mf#1]
Could you please give a short description on `input_counts` and `output_counts`? 
It seems like you are giving a matrix as in input to your NN, right? then what should be the `output_counts`? 
Thanks.

**Comment by MrChrisJohnson** [comment]
I apologize for the terrible documentation. This was a quick project that I put together over a weekend with the intention of coming back to clean it up at some point. 

Essentially, what we are doing is taking some input set of implicit observations (input_counts) and predict some output set of implicit observations from the future (output_counts). If you take the example of a music streaming recommender system, then ```input_counts``` would be songs that were played by each user over the last 1 year (with the last 2 weeks removed) and ```output_counts``` would be the songs that were played in the last 2 weeks.
