### ISSUE TITLE
An explanation about how to run the code with sample input and output

### ISSUE THREAD

**Issue by rahmanidashti** [MrChrisJohnson/deep-mf#2]
Hi,

Thanks for sharing the code, Chris. Could you please give some example of how to run the code? how to predict user's preference on items? I think the return of the training method is item vectors but where is the user vectors?

Also, it would be great if you complete it with the comparison section of Word2Vec and etc.

**Comment by MrChrisJohnson** [comment]
Sorry, but I don't have the time to provide a detailed write-up on this. Take a look at train_model(). input_counts and output_counts are 2d numpy arrays containing the implicit feedback input and output counts. The output of this function will be the vector embeddings.
